main/main1/routes.py
from flask import render_template, request, Blueprint
from flask_login import current_user, login_required
from main.model import Post, Email, User
import datetime
from sqlalchemy import func

import io
import random
from flask import Response
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib import pyplot as plt

main1 = Blueprint('main1', __name__) #create blueprint

#Home route
@main1.route("/")
@main1.route("/home")
def home():
	page = request.args.get('page', 1, type=int)
	posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=3) #orders the posts in a specfic order and shows 5 per page
	return render_template('home.html', posts=posts)

#About route
@main1.route("/about")
def about():
	return render_template('about.html', title='About')

#Welcome route
@main1.route("/welcome")
def welcome():
	return render_template('welcome.html', title='Welcome')

#Inbox route
@main1.route("/inbox_mail")
def inbox_mail():
	email_address = current_user.email
	query_set = Email.query.filter(Email.naive_bayes_spam != 1).filter(Email.to==email_address).order_by(Email.date_sent.desc()).all()
	for email in query_set:
		print(email.date_sent)
		print(email.sender)
		print(email.subject)
		print(email.body)
	return render_template('inbox_mail.html', title='Inbox Mail', query_set=query_set) 

#Sent route
@main1.route("/sent")
def sent():
	email_address = current_user.email
	query_set = Email.query.filter(Email.naive_bayes_spam != 1 and Email.sender==email_address).order_by(Email.date_sent.desc()).all()
	for email in query_set:
		print(email.date_sent)
		print(email.to)
		print(email.subject)
		print(email.body)
	return render_template('sent.html', title='Sent Mail', query_set=query_set)

#SpamReport route
@main1.route("/spam_report")
def spam_report():

	#Report 1
	today = datetime.date.today()
	seven_days_ago = today - datetime.timedelta(days=7)
	print(seven_days_ago)
	query_set = Email.query.filter(Email.naive_bayes_spam == 1).filter(Email.date_sent > seven_days_ago).count()
	print(query_set)

	#Report 2
	spam_by_account = Email.query.with_entities(Email.to, func.count(Email.id).label('count')).filter(Email.naive_bayes_spam == 1).group_by(Email.to).all()
	print(spam_by_account)

	#Report 3
	today = datetime.date.today()
	two_days_ago = today - datetime.timedelta(days=2)
	spam_email = Email.query.filter(Email.naive_bayes_spam == 1).filter(Email.date_sent > two_days_ago).all()

	return render_template('spam_report.html', title='Spam Report', query_set=query_set, spam_by_account=spam_by_account, spam_email=spam_email)

#SpamMail route
@main1.route("/spam_mail")
def spam_mail():
	email_address = current_user.email
	query_set = Email.query.filter(Email.to == email_address).filter(Email.naive_bayes_spam == 1).order_by(Email.date_sent.desc()).all()
	for email in query_set:
		print(email.date_sent)
		print(email.sender)
		print(email.subject)
		print(email.body)
		print(email.naive_bayes_spam)
	return render_template('spam_mail.html', title='Spam Mail', query_set=query_set)

#Registered_users route
@main1.route("/registered_users")
def registered_users():
	user_set = User.query.all() #this line outputs the first 3 columns in the USERS table
	print(user_set)

	return render_template('registered_users.html', title='Registered Users', user_set=user_set)

#Report 2 graph
@main1.route("/plot.png")
def plot_png():
    fig = create_figure()
    output = io.BytesIO()
    FigureCanvas(fig).print_png(output)
    return Response(output.getvalue(), mimetype='image/png')

def create_figure():
	fig = Figure()
	axis = fig.add_subplot(1, 1, 1)
	email = Email.query.with_entities(Email.to).filter(Email.naive_bayes_spam == 1).group_by(Email.to).all()
	email_result = [r for r, in email]
	count = Email.query.with_entities(func.count(Email.id).label('count')).filter(Email.naive_bayes_spam == 1).group_by(Email.to).all()
	count_result = [r for r, in count]
	axis.bar(email_result, count_result)
	return fig



main/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from main import db
from main.model import Post
from main.posts.forms import PostForm

posts = Blueprint('posts', __name__) #create blueprint

#Compose a new mail route
@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
	form = PostForm()
	if form.validate_on_submit():
		post = Post(title=form.title.data, content=form.content.data, author=current_user) #create email
		db.session.add(post) #add email to database
		db.session.commit()
		flash('Your email has been sent!', 'success')
		return redirect(url_for('main1.home'))
	return render_template('create_post.html', title='Compose Mail', form=form, legend='Compose Mail')

main/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from main import db, bcrypt
from main.model import User, Post
from main.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm, PostForm
#from main.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__) #create blueprint

#Register route
@users.route("/register", methods=['GET', 'POST']) #adding methods to allow for POST request
def register():
	if current_user.is_authenticated: #if current user is logged in redirect them to the home page
		return redirect(url_for('main1.home'))
	form = RegistrationForm()
	#Check if the data entered is validate for the form
	if form.validate_on_submit():#CHECKING IF FORM IS VALIDATE ON SUBMIT
		#Hash Password
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password) #creates a new user
		db.session.add(user) #add this user to the changes in our db
		db.session.commit() #commit these changes this will add the user to the database
		flash('Your account has now been created! You are now able to log in', 'success') #flash one time alert message, f string is used as we are passing in a variable
		#redirect to the home page after a successful creation
		return redirect(url_for('users.login')) #login is the name of the function of the route, user is returned to login page
	return render_template('register.html', title='Register', form=form)


#Login route
@users.route("/login", methods=['GET', 'POST'])
def login():
	if current_user.is_authenticated: #if current user is logged in redirect them to the home page
		return redirect(url_for('main1.home'))
	form = LoginForm()
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first() #this will filter the emails entered into the form to see if this email exist already in the db and if it does exist returnt he first user with this email
		if user and bcrypt.check_password_hash(user.password, form.password.data): #this will check the hash password with the password they enter into the form
			login_user(user, remember=form.remember.data) #this will login the user
			next_page = request.args.get('next') #get next parameter from url if user exists (get method)
			return redirect(next_page) if next_page else redirect(url_for('main1.welcome')) #redirect to the next page if the next page exists if it is null of false return the redirect to home page
		else:
			flash('Login unsuccessful. Please check email and password', 'danger') #danger will display a red alert
	return render_template('login.html', title='Login', form=form) #return login page


#Logout route
@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for('main1.home'))


#Account route
#This is used if a user clicks on a certain link and they need to be logged in order to view this data
@users.route("/account", methods=['GET', 'POST']) #allowing GET and POST requests
@login_required #this means we need to be logged in to access the account route
def account():
	form = UpdateAccountForm()
	#if form.validate_on_submit(): #validate form
		#if form.picture.data: #check for picture data
			#set users profile pic (create new function for this above in the code)
		#	picture_file = save_picture(form.picture.data)
		#	current_user.image_file = picture_file
		#current_user.username = form.username.data #we can update our username and email
		#current_user.email = form.email.data
		#db.session.commit()
		#flash('Your account has been updated!', 'success')
		#return redirect(url_for('users.account'))
	if request.method == 'GET': #populate form when user visits account page
		form.username.data = current_user.username
		form.email.data = current_user.email
		#form.password.data = current_user.password 
	#image_file = url_for('static', filename='profile_pics/' + current_user.image_file) #set imagefile to static dir
	return render_template('account.html', title='Account', form=form) #image_file=image_file


#User Posts route
#@users.route("/user/<string:username>")
#def user_posts(username):
#	page = request.args.get('page', 1, type=int)
#	user = User.query.filter_by(username=username).first_or_404() #get the first user with this username
#	posts = Post.query.filter_by(author=user)\
		#.order_by(Post.date_posted.desc())\
		#.paginate(page=page, per_page=3) #orders the posts in a specfic order and shows 5 per page
#	return render_template('user_posts.html', posts=posts, user=user)

#Route Request to reset password
@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
	if current_user.is_authenticated: #make sure user is logged out before resetting password
		return redirect(url_for('main1.home'))
	form = RequestResetForm()
	if form.validate_on_submit(): #they have no submitted an email into the form
		user = User.query.filter_by(email=form.email.data).first() #get user for that email
		send_reset_email(user) #send email to the user
		flash('An email has been sent with instructions to reset your password.', 'info')
		return redirect(url_for('users.login'))
	return render_template('reset_request.html', title='Reset Password', form=form)


#Reset their password actually
#@users.route("/reset_password/<token>", methods=['GET', 'POST'])
#ef reset_token(token): #verify token from URL using the user method created
#	if current_user.is_authenticated: #make sure user is logged out before resetting password
#		return redirect(url_for('main1.home'))
#	user = User.verify_reset_token(token) 
#	if user is None:
#		flash('That is an invalid or expired token', 'warning')
#		return redirect(url_for('users.reset_request'))
#	form = ResetPasswordForm()
#	if form.validate_on_submit():#CHECKING IF FORM IS VALIDATE ON SUBMIT
#		#Hash Password
#		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
#		user.password = hashed_password #hashing the users password from form.password.data
#		db.session.commit() #commit these changes to the users password
#		flash('Your password has been updated! You are now able to log in', 'success') #flash one time alert message, f string is used as we are passing in a variable
#		#redirect to the home page after a successful creation
#		return redirect(url_for('users.login'))
#	return render_template('reset_token.html', title='Reset Password', form=form)

main/templates/about.html
{% extends "base.html" %}
{% block content %}
<h2>About ByeHackers...</h2>
<hr>
	<p>ByeHackers is a spam filter tool.</p>
	<p>It provides protection and preventetion to all customers at the highest level possible.</p>
	<p>ByeHackers aim is to help stop the fight against spam.</p>
<hr>
	<p>ByeHackers uses Machine Learning algorithms to classify an email as spam or ham.</p>
	<p>The following Machine Learning algorithms are used:</p>

	<button class="button button1">Naive Bayes</button>
	<button class="button button1">Support Vector Machine</button>
	<button class="button button1">Random Forest</button>
	<button class="button button1">Logistic Regression</button>
<hr>

	<p><b>Naive Bayes</b></p>
	<p>NB algorithm is a supervised learning algorithm, which is based on Bayes theorem and used for solving classification problems</p>
<hr>
	<p><b>Support Vector Machine</b></p>
	<p>SVM is a supervised machine learning algorithm which can be used for both classification or regression challenges. However, it is mostly used in classification problems</p>
<hr>
	<p><b>Random Forest</b></p>
	<p>It is a flexible, easy to use machine learning algorithm that produces, a great result. It is also one of the most used algorithms, because of its simplicity and diversity as it can be used for both classification and regression tasks.</p>
<hr>
	<p><b>Logistic Regression</b></p>
	<p>The algorithm is used for the classification problems. It is a predictive analysis algorithm and based on the concept of probability.</p>
<hr>
{% endblock content %}

main/templates/account.html
{% extends "base.html" %}
{% block content %}
	<div class="content-section" align="left">
		<form method="POST" action="" enctype="multipart/form-data"> <!--add encoding type so image data is passed correct within the form-->
			{{ form.hidden_tag() }} <!--Protects against XSS and CSRF attacks-->
			<fieldset class="col-sm-8 form-group">
				<div class="h2">Account Information</h2></div>
				<hr>
				<!--Username Form group-->
				<div class="col-sm-8 form-group">
					{{ form.username.label(class="form-control-label")}} <!--Prints username label-->
						{{ form.username(class="form-control form-control-lg", disabled=True)}}
				</div>

				<!--Email Form group-->
				<div class="col-sm-8 form-group">
					{{ form.email.label(class="form-control-label")}} <!--Prints email label-->
						{{ form.email(class="form-control form-control-lg", disabled=True)}}
				</div>
			</fieldset>
		</form>
	</div>
{% endblock content %}



main/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  {% if title %}
    <title>ByeHackers - {{ title }}</title>
  {% else %}
    <title>ByeHackers</title>
  {% endif %}
  <style>

    /* Remove the navbar's default margin-bottom and rounded borders */ 
    .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    .form-control-label {
      text-align: left;
    }
    
    /* Set height of the grid so .sidenav can be 100% (adjust as needed) 450px*/
    .row.content {height: 790px} 
    
    /* Set gray background color and 100% height */
    .sidenav {
      padding-top: 18px;
      background-color: #f1f1f1;
      height: 100%;
      position: relative;
    }

    .forms {
      padding: 15px;
    }
    
    body {
      height: 100%;
      min-height: 100%;
      overflow: auto;
    }

    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 10px;
      clear: both;
      position: relative;
      height: 60px;
      margin-top: -60px;
      width: 100%;
    }
    
    /* On small screens, set height to 'auto' for sidenav and grid */
    @media screen and (max-width: 767px) {
      .sidenav {
        height: 100%;
        padding: 15px;
      }
      .row.content {height:auto;} 
    }

    .btn-default {
      background: #000;
      color: #fff;
      box-shadow: 1px 2px 5px #000000;
      width: 48%;

      /*float: center;*/
   }

   .btn1-default {
      background: #000;
      color: #fff;
      box-shadow: 1px 2px 5px #000000;
      width: 15%;
   }

  .btn-default:hover {
      background: #FFFFFF;
      color: #000;
   }

   .btn1-default:hover {
      background: #FFFFFF;
      color: #000;
   }

   .btn-outline-info {
      width: 35%; 
      background: #808080;
      cursor: pointer;
      color: #FFFFFF;
   }

  .carousel-control.right, .carousel-control.left {
   background-image: none;
   color: #FF0000;
  }

  .carousel-indicators li {
    border-color: #FF0000;
  }

  .carousel-indicators li.active {
    background-color: #FF0000;
  }

  .item h4 {
    font-size: 19px;
    line-height: 1.375em;
    font-weight: 400;
    font-style: italic;
    margin: 50px 0;
  }

  .item span {
    font-style: normal;
  }

  .button {
  align-items: center;
  color: white;
  padding: 20px 32px;
  text-align: center;
  font-weight: bold;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
}

.button1 {
  background-color: #ffeeed; 
  color: black; 
  border: 4px solid #FF0000;
}

.invalid-feedback {
  color: red;
  background: #ffe0e0;
  border: 1px solid #a33a3a; 
}

.myTable { 
  border: 0px solid #69899F;
  width: 100%;
  }

.myTable th { 

padding:15px;
    color:#fff;
    text-shadow:1px 1px 1px #568F23;
    border-bottom:3px solid #9ED929;
    background-color:#9DD929;
    background:-webkit-gradient(
        linear,
        left bottom,
        left top,
        color-stop(0.02, rgb(123,192,67)),
        color-stop(0.51, rgb(139,198,66)),
        color-stop(0.87, rgb(158,217,41))
        );
    background: -moz-linear-gradient(
        center bottom,
        rgb(123,192,67) 3%,
        rgb(139,198,66) 52%,
        rgb(158,217,41) 88%
        );
    -webkit-border-top-left-radius:5px;
    -webkit-border-top-right-radius:5px;
    -moz-border-radius:5px 5px 0px 0px;
    border-top-left-radius:5px;
    border-top-right-radius:5px;
  }

.myTable td {
    width:100px;
    padding:10px;
    text-align:center;
    vertical-align: top;
    background-color:#DEF3CA;
    border: 1px solid #BED3AB;
    -moz-border-radius:2px;
    -webkit-border-radius:2px;
    border-radius:2px;
    color: black;
    text-shadow:1px 1px 1px #fff;
}

.h2 {
  text-align: left;
  color: black;
}

.form-group {
  align-content: left;
}
</style>
</head>
<body>

<nav class="navbar navbar-inverse"> <!-- puts the black colour into the nav bar-->
  <div class="container-fluid">
      <a class="navbar-brand disabled">ByeHackers</a> 
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('main1.welcome') }}"><span class="glyphicon glyphicon-ok"> Authenicated</a></li>
        {% else %}
        <li><a href="{{ url_for('main1.home') }}"><span class="glyphicon glyphicon-home"> Home</a></li>
        <li><a href="{{ url_for('main1.about') }}"><span class="glyphicon glyphicon-info-sign"> About</a></li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('users.account') }}"><span class="glyphicon glyphicon-user"></span> Account</a></li>
        <li><a href="{{ url_for('users.logout') }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
        {% else %}
        <li><a href="{{ url_for('users.login') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        <li><a href="{{ url_for('users.register') }}"><span class="glyphicon glyphicon-log-in"></span> Register</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid text-center">    
  <div class="row content">
    <div class="col-sm-2 sidenav">
      {% if current_user.is_authenticated %}
      <p><a href="{{ url_for('posts.new_post') }}">Compose </a><span class="glyphicon glyphicon-pencil"></span></p> <!-- posts.post.new --> 
      <p><a href="{{ url_for('main1.inbox_mail') }}">Inbox </a><span class="glyphicon glyphicon-save"></span></p>
      <p><a href="{{ url_for('main1.sent') }}">Sent </a><span class="glyphicon glyphicon-open"></span></p>
      <p><a href="{{ url_for('main1.spam_mail') }}">Spam </a><span class="glyphicon glyphicon-exclamation-sign"></span></p>
      {% if current_user.is_admin %}
      <p><a href="{{ url_for('main1.spam_report') }}">Spam Report </a><span class="glyphicon glyphicon-list-alt"></span></p>
      <p><a href="{{ url_for('main1.registered_users') }}">Registered Users </a><span class="glyphicon glyphicon-list-alt"></span></p>
      {% endif %}
      <p><a href="{{ url_for('users.account') }}">Account </a><span class="glyphicon glyphicon-user"></span></p>
      <p><a href="{{ url_for('users.logout') }}">Logout </a><span class="glyphicon glyphicon-log-out"></span></p>  
      <!--ADMIN USER DISPLAY SPAM REPORT AND ALL REGISTERED USERS OF THE WEB APP-->
      {% else %}
      <!--DONT DISPLAY THE SIDENAV IF THE USER IS NOT LOGGED IN-->
      {% endif %}
    </div>

    <div class="col-sm-8 text-left"> 
      <div class="col-md-8">
      <!--display flash messages-->
      {% with messages = get_flashed_messages(with_categories=true) %}
      <!--return any messages from the with flash function-->
      {% if messages %} <!-- if messages is not empty then we have flash messages to display-->
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}"><!-- prints out the messages-->
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% endwith %} <!--close endwith code block-->
    </div>
  
      <div id="content">
        {% block content %}{% endblock %}
      </div>
    </div>
    <div class="col-sm-2 sidenav"> <!--right side nav-->
      {% if current_user.is_authenticated %} <!--if the user is logged in-->
      <p></p>
      {% else %}
      <div class="well">
        <p><b>STATS</p></b>
      </div>
      <div class="well">
        <p>&#9888; 53.95% of e-mail traffic in March 2020 was spam.</p> 
      </div>
      <div class="well">
        <p>&#9888; Email spam costs businesses $20.5 billion every year.</p>
      </div>
      <div class="well">
        <p>&#9888; Around 107 billion spam emails are sent per day. By 2024, the figure is expected to increase to over 361.6 billion daily mails.</p>
      </div>
      <div class="well">
        <p>&#9888; Bulk mailers can send approximately 250,000 messages an hour over a 28.8kb/s modem line.</p>
      </div>
    </div>
    {% endif %}
  </div>
</div>

<footer class="container-fluid text-center"> <!--footer-->
  <p>Copyright &#169 2021 byehackers.com. All rights reserved.</p>
</footer>

</body>
</html>

main/templates/error_message.html
{% extends "base.html" %}
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  {% if title %}
    <title>ByeHackers - {{ title }}</title>
  {% else %}
    <title>ByeHackers</title>
  {% endif %}
</head>
<body>
  <header class="site-header"> <!-- Nav bar starts -->
  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
    <div class="container">
      <a class="navbar-brand mr-4" href="/">Spam Checker</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarToggle">
        <div class="navbar-nav mr-auto">
          <a class="nav-item nav-link" href="{{ url_for('main1.home') }}">Home</a> 
          <a class="nav-item nav-link" href="{{ url_for('main1.about') }}">About</a>
        </div>
        <!-- Navbar Right Side -->
        <div class="navbar-nav">
          {% if current_user.is_authenticated %} <!--this means the user is logged in-->
            <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
            <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
          {% else %} <!--if their not logged in we want to show them the login and register route-->
            <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
            <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
</header> <!-- Nav bar ends -->

  <main role="main" class="container"> <!-- Main starts -->
  <div class="row">
    <div class="col-md-8">
      <!--display flash messages-->
      {% with messages = get_flashed_messages(with_categories=true) %}
      <!--return any messages from the with flash function-->
      {% if messages %} <!-- if messages is not empty then we have flash messages to display-->
        {% for category, message in messages %}
          <div class="alert alert-{{ category }}"><!-- prints out the messages-->
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      {% endwith %} <!--close endwith code block-->
      {% block content %}{% endblock %}
    </div>
  </div>
</main> 
</body>
</html>

main/templates/home.html
{% extends "base.html" %}
{% block content %}
      {% if current_user.is_authenticated %}
            <p></p>
      {% else %}
            <h2>Welcome to ByeHackers...</h2>
            <hr>
            <div class="text-center">
                  <img src="{{url_for('static', filename='spam_filter_home.png')}}" class="rounded"/>
            </div>
             <hr>
            <p>Find out more about ByeHackers, <button class="btn btn1-default"><a href="{{ url_for('main1.about') }}"> CLICK HERE</a></p></button>
            <hr>
            <p>Choose one of the following options to access the application:</p>
            <button class="btn btn-default"><a href="{{ url_for('users.register') }}"><span class="glyphicon glyphicon-log-in"></span> Register</a></button>&nbsp;&nbsp;&nbsp;&nbsp;
            <button class="btn btn-default"><a href="{{ url_for('users.login') }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></button>
      {% endif %}
            <hr>
            <p></p>
{% endblock content %}

main/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="forms">
	</div>
	<div class="content=section">
		<div class="col-sm-8 text-left">
		<form method="POST" action="">
			{{ form.hidden_tag() }} <!--Protects against XSS and CSRF attacks-->
			<div></div>
			<fieldset class="form-group">
				<legend class="border-bottom mb-4"> Login</legend>

				<!--Email Form group-->
				<div class="form-group">
					{{ form.email.label(class="form-control-label")}} <!--Prints username label and bootstrap added-->
					<!--Print validation errors-->
					<!--checking if the data entered is valid in the form and if not display errors to the user-->
					{% if form.email.errors %}
						{{ form.email(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.email.errors %}
								<span>{{ error }}</span> <!--prints out the errors-->
							{% endfor %}
						</div>
					{% else %}
						{{ form.email(class="form-control form-control-lg")}}
					{% endif %}
				</div>
				
				<!--Password Form group-->
				<div class="form-group">
					{{ form.password.label(class="form-control-label")}} <!--Prints username label -->
					<!--Print validation errors-->
					<!--checking if the data entered is valid in the form and if not display errors to the user-->
					{% if form.password.errors %}
						{{ form.password(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.password.errors %}
								<span>{{ error }}</span> <!--prints out the errors-->
							{% endfor %}
						</div>
					{% else %}
						{{ form.password(class="form-control form-control-lg")}}
					{% endif %}
				</div>

				<!--Remember Me Field, this will be a bootsrap class-->
				<div class="form-check">
					{{ form.remember(class="form-check-input") }}
					{{ form.remember.label(class="form-check-label") }}
				</div>
			</fieldset>

			<!--Login-->
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info")}}<!-- this will display as a button-->
				<hr>
				<!--Forgot Password-->
				<small class="text-muted ml-2">
					<a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
				</small>
			</div>

			<hr>
			<div class="form-group">

			<small class="text-muted"> <!--faded out text-->
			Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
		</small>
	</div>
		</form>
	</div>
</div>
{% endblock content %}

main/templates/welcome.html
{% extends "base.html" %}
{% block content %}

<h1>Welcome, {{ current_user.username }}</h1>
<p>You are now logged in and can begin using the application...</p>
{% endblock content %}